### ISSUE TITLE
python cifar_example.py --opt sasa error

### ISSUE THREAD

**Issue by jackweiwang** [microsoft/statopt#1]
Start training ...
    epoch   1: average loss 0.017
    epoch   2: average loss 0.012
    epoch   3: average loss 0.010
    epoch   4: average loss 0.009
    epoch   5: average loss 0.008
    epoch   6: average loss 0.008
    epoch   7: average loss 0.008
    epoch   8: average loss 0.007
    epoch   9: average loss 0.007
    epoch  10: average loss 0.007
    epoch  11: average loss 0.006
Traceback (most recent call last):
  File "cifar_example.py", line 94, in <module>
    optimizer.step()
  File "/home/ww/anaconda3/envs/py3.6/lib/python3.6/site-packages/statopt/sasa.py", line 127, in step
    self.stats_adaptation()
  File "/home/ww/anaconda3/envs/py3.6/lib/python3.6/site-packages/statopt/sasa.py", line 156, in stats_adaptation
    bucket.add(self.state['stats_val'])
  File "/home/ww/anaconda3/envs/py3.6/lib/python3.6/site-packages/statopt/bucket.py", line 51, in add
    self.buffer[0:self.count] = self.buffer[self.start:self.end] 
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.

pytorch 1.4.0

**Comment by pzzhang** [comment]
Thank you for identifying this problem! We fixed this bug in this recent commit. 

https://github.com/microsoft/statopt/commit/75f4c239a34d6d5182bc575dba8745ef39b28072

We will update the statopt soon. Before that, you can use the source code to import the optimizer.

**Comment by jackweiwang** [comment]
ok
